repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        files: (^pyscf_ipu/experimental/)|(^test/)|(\.(cfg|txt|flake8|ini))
    -   id: trailing-whitespace
        files: (^pyscf_ipu/experimental/)|(^test/)

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black-jupyter
        files: (^pyscf_ipu/experimental/)|(^test/)
        name: Format code

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: (^pyscf_ipu/experimental/)|(^test/)
        name: Sort imports

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        files: (^pyscf_ipu/experimental/)|(^test/)
        name: Check PEP8

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--select=C]
        additional_dependencies: [flake8-copyright]
        name: copyright check