[project]
name = "pyscf_ipu"
description = "PySCF  on the Graphcore IPU"
version = "0.1"
authors = [
    { name = "Alex Mathiasen", email = "alexm@graphcore.ai" }
]

[tool.setuptools]
packages = [
   "pyscf_ipu"
]

